let SHOP_NAME = process.env.REACT_APP_SHOP_NAME
SHOP_NAME = SHOP_NAME.split(" ")[0]
export const local_expirationDate = `${SHOP_NAME}_expirationDate`
export const local_category = `${SHOP_NAME}_category`
export const local_cart_storage = `${SHOP_NAME}_cart_storage`
export const local_searchText = `${SHOP_NAME}_searchText`
export const local_userName = `${SHOP_NAME}_userName`
export const local_userPhone = `${SHOP_NAME}_userPhone`
export const local_userAddress = `${SHOP_NAME}_userAddress`
export const local_userCode = `${SHOP_NAME}_userCode`
export const local_userService = `${SHOP_NAME}_userService`
export const local_userPayment = `${SHOP_NAME}_userPayment`
export const local_userDepartment = `${SHOP_NAME}_userDepartment`
export const local_userEmail = `${SHOP_NAME}_userEmail`
